apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - provider-family.yaml
  - provider-nosql.yaml
  - function-patch-and-transform.yaml
  # providerconfig.yaml re-added once the OCI provider CRDs are registered
